{"name": "登录失败", "status": "broken", "statusDetails": {"message": "TypeError: click() takes 1 positional argument but 2 were given", "trace": "self = <cases.test_loginfail.Test_Loginfail object at 0x7fa748bbf520>\nlistcases = ['点击登录', 'click', 'xpath=//*[@id=\"loginform\"]/div/div[6]/a']\n\n    @pytest.mark.parametrize('listcases', datas['loginfailPage'])\n    @allure.story(\"用户登陆\")\n    @pytest.mark.login\n    @pytest.mark.run(order=1)\n    def test_loginfail(self, listcases):\n        allure.dynamic.title(listcases['title'])  # 获取yaml中的title\n    \n        testcase = listcases['cases']\n        for cases in testcase:\n            listcases = list(cases.values())  # 获取字典列表值\n            with allure.step(listcases[0]):\n                func = getattr(self.web, listcases[1])\n                values = listcases[2:]\n>               func(*values)\n\ncases/test_loginfail.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <common.initialization.Comm object at 0x7fa748b937f0>\nlocator = 'xpath=//*[@id=\"loginform\"]/div/div[6]/a', value = None\n\n    def click(self, locator=None,value = None):\n        \"\"\"\n        找到并点击元素\n        :param locator: 定位器，默认Xpath\n        :return:\n        \"\"\"\n        ele = self.__find_ele(locator)\n>       ele.click(str(value))\nE       TypeError: click() takes 1 positional argument but 2 were given\n\ncommon/initialization.py:81: TypeError"}, "steps": [{"name": "打开登录页", "status": "passed", "start": 1622197628016, "stop": 1622197628317}, {"name": "输入用户名", "status": "passed", "start": 1622197630318, "stop": 1622197630413}, {"name": "输入密码", "status": "passed", "start": 1622197632416, "stop": 1622197632476}, {"name": "输入验证码", "status": "passed", "start": 1622197634480, "stop": 1622197634538}, {"name": "点击登录", "status": "broken", "statusDetails": {"message": "TypeError: click() takes 1 positional argument but 2 were given\n", "trace": "  File \"/Users/liuyue/Desktop/workspace/cases/test_loginfail.py\", line 37, in test_loginfail\n    func(*values)\n  File \"/Users/liuyue/Desktop/workspace/common/initialization.py\", line 81, in click\n    ele.click(str(value))\n"}, "start": 1622197636540, "stop": 1622197636557}], "parameters": [{"name": "listcases", "value": "{'title': '登录失败', 'cases': [{'name': '打开登录页', 'method': 'geturl', 'url': 'http://testingedu.com.cn:8000/index.php/Home/user/login.html'}, {'name': '输入用户名', 'method': 'input', 'locator': 'xpath=//*[@id=\"username\"]', 'value': 13800138006}, {'name': '输入密码', 'method': 'input', 'locator': 'xpath=//*[@id=\"password\"]', 'value': 123456555}, {'name': '输入验证码', 'method': 'input', 'locator': 'xpath=//*[@id=\"verify_code\"]', 'value': 111111}, {'name': '点击登录', 'method': 'click', 'locator': 'xpath=//*[@id=\"loginform\"]/div/div[6]/a'}, {'name': '固定等待', 'method': 'sleep', 'time': 2}]}"}], "start": 1622197628016, "stop": 1622197636558, "uuid": "b0902b6b-4aea-4cd1-9171-84edf61e13de", "historyId": "3d1f0b6cffcd0489525db73c0191dca1", "testCaseId": "c6b4e6488c615a65ac4b1d18394d879c", "fullName": "cases.test_loginfail.Test_Loginfail#test_loginfail", "labels": [{"name": "story", "value": "用户登陆"}, {"name": "feature", "value": "用户登陆失败"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_loginfail"}, {"name": "subSuite", "value": "Test_Loginfail"}, {"name": "host", "value": "liuyuedeMacBook-Pro.local"}, {"name": "thread", "value": "36132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_loginfail"}]}